In [33]:
import numpy as np
def GaussianElim(a,b):
    A = a.astype('float64')
    B = b.astype('float64')
    x = np.zeros_like(B)
    print(A)
    m, n = A.shape
    assert m==n==len(b)
    for k in range(n-1):
        for j in range(k+1,n):
            A[j,k+1:n] -= A[j,k]/A[k,k]*A[k,k+1:n]
            B[j] -= A[j,k]/A[k,k]*B[k]
    
    # Backward substitution
    for k in range(n-1,-1,-1):
        x[k] = (B[k]-A[k,k+1:n]@x[k+1:n])/A[k,k]
    
    return x

In [34]:
A = np.array([[1,2,3],[1,3,1],[2,2,4]])
b = np.array([1,1,1])

In [35]:
x = GaussianElim(A,b)

[[1. 2. 3.]
 [1. 3. 1.]
 [2. 2. 4.]]


In [36]:
x

array([-0.16666667,  0.33333333,  0.16666667])