In [16]:
import numpy as np
def GaussianElim(a,b):
    A = a.astype('float64')
    B = b.astype('float64')
    x = np.zeros_like(B)
    m, n = A.shape
    assert m==n==len(b)
    for k in range(n-1):
        for j in range(k+1,n):
            alpha = A[j,k]/A[k,k]
            A[j,k:n] -= alpha*A[k,k:n]
            B[j] -= alpha*B[k]
            print(A,B)
    
    # Backward substitution
    for k in range(n-1,-1,-1):
        x[k] = (B[k]-A[k,k+1:n]@x[k+1:n])/A[k,k]
    
    return x

In [17]:
A = np.array([[1,2,3],[1,3,1],[2,2,4]])
b = np.array([1,1,1])

In [19]:
x = GaussianElim(A,b)

[[ 1.  2.  3.]
 [ 0.  1. -2.]
 [ 2.  2.  4.]] [1. 0. 1.]
[[ 1.  2.  3.]
 [ 0.  1. -2.]
 [ 0. -2. -2.]] [ 1.  0. -1.]
[[ 1.  2.  3.]
 [ 0.  1. -2.]
 [ 0.  0. -6.]] [ 1.  0. -1.]


In [20]:
x

array([-0.16666667,  0.33333333,  0.16666667])

In [21]:
A = np.array([[1,2,3],[1,2,1],[2,2,4]])
b = np.array([1,1,1])

In [22]:
x = GaussianElim(A,b) # in this case, we need to do pivoting. 

[[ 1.  2.  3.]
 [ 0.  0. -2.]
 [ 2.  2.  4.]] [1. 0. 1.]
[[ 1.  2.  3.]
 [ 0.  0. -2.]
 [ 0. -2. -2.]] [ 1.  0. -1.]
[[  1.   2.   3.]
 [  0.   0.  -2.]
 [  0.  nan -inf]] [ 1.  0. nan]


C:\Users\016205356\AppData\Local\Temp\ipykernel_7832\1052928441.py:10: RuntimeWarning: divide by zero encountered in double_scalars
  alpha = A[j,k]/A[k,k]
C:\Users\016205356\AppData\Local\Temp\ipykernel_7832\1052928441.py:11: RuntimeWarning: invalid value encountered in multiply
  A[j,k:n] -= alpha*A[k,k:n]
C:\Users\016205356\AppData\Local\Temp\ipykernel_7832\1052928441.py:12: RuntimeWarning: invalid value encountered in double_scalars
  B[j] -= alpha*B[k]


In [33]:
def GaussianElim_pivot(a,b, eps=0.00001):
    A = a.astype('float64')
    B = b.astype('float64')
    x = np.zeros_like(B)
    m, n = A.shape
    assert m==n==len(b)
    for k in range(n-1):
        if (abs(A[k,k])<eps):
            # First, we need to find the index k_sw that has max A[k:n,k]
            k_sw = np.argmax(abs(A[k:n,k]))+k
            # swap row k with the row k_sw that has max A[k:n,k]
            A[[k, k_sw]] = A[[k_sw, k]]
            B[[k, k_sw]] = B[[k_sw, k]]
        for j in range(k+1,n):
            alpha = A[j,k]/A[k,k]
            A[j,k:n] -= alpha*A[k,k:n]
            B[j] -= alpha*B[k]
            print(A,B)
    
    # Backward substitution
    for k in range(n-1,-1,-1):
        x[k] = (B[k]-A[k,k+1:n]@x[k+1:n])/A[k,k]
    
    return x

In [35]:
x = GaussianElim_pivot(A,b)

[[ 1.  2.  3.]
 [ 0.  0. -2.]
 [ 2.  2.  4.]] [1. 0. 1.]
[[ 1.  2.  3.]
 [ 0.  0. -2.]
 [ 0. -2. -2.]] [ 1.  0. -1.]
[[ 1.  2.  3.]
 [ 0. -2. -2.]
 [ 0.  0. -2.]] [ 1. -1.  0.]


In [36]:
print(x)

[ 0.   0.5 -0. ]


In [37]:
A@x - b

array([0., 0., 0.])

In [50]:
# Another way to implement Gaussian Elimination, get rid of the inner for loop. 
def GaussianElim_pivot_v2(a,b, eps=0.00001):
    A = a.astype('float64')
    B = b.astype('float64')
    x = np.zeros_like(B)
    m, n = A.shape
    assert m==n==len(b)
    for k in range(n-1):
        if (abs(A[k,k])<eps):
            # First, we need to find the index k_sw that has max A[k:n,k]
            k_sw = np.argmax(abs(A[k:n,k]))+k
            # swap row k with the row k_sw that has max A[k:n,k]
            A[[k, k_sw]] = A[[k_sw, k]]
            B[[k, k_sw]] = B[[k_sw, k]]
        alpha = A[k+1:n,k]/A[k,k]
        A[k+1:n,k:n] -= np.outer(alpha,A[k,k:n])
        B[k+1:n] -= alpha*B[k+1:n]
        print(A,B)
    
    # Backward substitution
    for k in range(n-1,-1,-1):
        x[k] = (B[k]-A[k,k+1:n]@x[k+1:n])/A[k,k]
    
    return x

In [51]:
x = GaussianElim_pivot_v2(A,b)

[[ 1.  2.  3.]
 [ 0.  0. -2.]
 [ 0. -2. -2.]] [ 1.  0. -1.]
[[ 1.  2.  3.]
 [ 0. -2. -2.]
 [ 0.  0. -2.]] [ 1. -1.  0.]


In [52]:
x

array([ 0. ,  0.5, -0. ])

In [53]:
A@x-b

array([0., 0., 0.])